level = "info"                                  # default level
formatter = "console_no_color"                  # console_no_color, json 도 가능
caller = true                                   # 소스 코드명과 라인 프린트
timefieldformat = "Jan _2 15:04:05.000"
​
[chain]                                         # 이렇게 여러개 쓸수 있음
level = "info"
​
[dpos]                                          # 이렇게 여러개 쓸수 있음
level = "warn"
​
[consensus]                                     # 이렇게 여러개 쓸수 있음
level = "debug"
​
[p2p]                                           # 이렇게 여러개 쓸수 있음
level = "debug"
​
[raft]
level = "debug"
​
[rafthttp]
level = "info"
​
[mempool]
level = "warn"
​
[syncer]                                        # 이렇게 여러개 쓸수 있음
level = "debug"level = "info"                   # default log level
formatter = "console"                           # format: console, console_no_color, json
caller = true                                   # enabling source file and line printer
timefieldformat = "Jan _2 15:04:05"
