version: '3.2'
services:
  indexer_check:
    container_name: indexer_check
    image: indexer
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
     - 8001:8001
    privileged: true
    network_mode: host
    command: indexer
      - --aergo=localhost:7845
      - --dburl=localhost:9200
      - --prefix=testnet
      - --mode=check
      - --from=0
      - --to=0
      - --cluster=false