version: '3.2'
services:
  indexer_onsync:
    container_name: indexer_onsync
    image: indexer
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
     - 8000:8000
    privileged: true
    network_mode: host
    command: indexer
      - --aergo=localhost:7845
      - --dburl=localhost:9200
      - --prefix=testnet
      - --mode=onsync
      - --cluster=false