version: '3.2'
services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    ulimits:
     memlock:
      soft: -1
      hard: -1
    volumes:
      - type: bind
        source: ./data/eldata/data
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./data/eldata/logs
        target: /usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200